### PR TITLE
Show a warning message if database is corrupted

### LINKED ISSUE #116: Show a warning message if database is corrupted
Currently, there is no proper handling of corrupted database files on application launch. Let's show a warning message if this happens.

### LINKED ISSUE #129: Invalid json may cause loss of data
If a user attempts to modify the storage json file manually and makes it invalid such as by having duplicate persons, the application will fail to load the contacts. If the user then enters any command, the json file will be overriden, potentially causing loss of data.

Related to #116.

### PR DESCRIPTION
**Pull request by aureliony**
Closes #116
Closes #129

### CODE REVIEW

File: src/main/java/seedu/address/MainApp.java [hunk 1]
```diff
@@ -138,10 +142,30 @@ protected UserPrefs initPrefs(UserPrefsStorage storage) {
...
+            initialAddressBook = new AddressBook();
+            initialWelcomeMessage = "WARNING!! Entering a command will override the old data file.\n"
+                    + e.getMessage();
+        }
+        return initialAddressBook;
+    }
+
     @Override
     public void start(Stage primaryStage) {
-        logger.info("Starting AddressBook " + MainApp.VERSION);
```
Comment (bryanyee33) [inline src/main/java/seedu/address/MainApp.java:143]: Should the version number be removed? It would be useful for debugging purposes in real-world scenarios.

Comment (aureliony) [reply src/main/java/seedu/address/MainApp.java:143]: Re-added
