### PR TITLE
 Reduce Coupling between Components

### LINKED ISSUE #277: StorageException is unnecessary
StorageException is unnecessary, as the existing DataLoadingException from AB3 has the same purpose.
Moreover, it causes unnecessary dependencies such the Main component depending on Storage component.

Let's switch all used instances into DataLoadingException instead.

### PR DESCRIPTION
**Pull request by bryanyee33**
* Fixes #277

### CODE REVIEW

File: src/main/java/seedu/address/ui/UiManager.java [hunk 1]
```diff
@@ -41,7 +41,7 @@ public void start(Stage primaryStage) {
         primaryStage.getIcons().add(getImage(ICON_APPLICATION));
 
         // Load custom fonts
-        Font.loadFont(getClass().getResourceAsStream("/styles/JetBrainsMono-SemiBold.ttf"), 16);
+        Font.loadFont(getClass().getResourceAsStream(CUSTOM_FONT), 16);
```
Comment (yisiox) [inline src/main/java/seedu/address/ui/UiManager.java:44]: Good catch on this magic string.

**Review by yisiox — APPROVED** [review]
LGTM

**Review by aureliony — APPROVED** [review]
LGTM
